name: cs_repository
description: Dart package which manages the cs firestore.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0


environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  cloud_firestore: ^4.2.0
  shared_repository:
    path: ../shared_repository
#
#  fuel_abc_shared_preferences:
#      path: ../fuel_abc_shared_preferences


dev_dependencies: 
  flutter_lints: ^2.0.1
  lints: ^2.0.0
