// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk9PkLBwKc21J35hgP0SBaL-gbd01sXVw',
    appId: '1:937397677110:web:d3fcda3d2027f19b88fc97',
    messagingSenderId: '937397677110',
    projectId: 'bsccs-4a473',
    authDomain: 'bsccs-4a473.firebaseapp.com',
    storageBucket: 'bsccs-4a473.appspot.com',
    measurementId: 'G-SY29Y9L7VV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUtO8L8fTyMPuOYBLU7vQdKKsjfhmJZPc',
    appId: '1:937397677110:android:977b97442d935c6088fc97',
    messagingSenderId: '937397677110',
    projectId: 'bsccs-4a473',
    storageBucket: 'bsccs-4a473.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY1WSWJwqu7OC8IgvEbJbgpIInDLZvHoU',
    appId: '1:937397677110:ios:de0dcd2126d8613588fc97',
    messagingSenderId: '937397677110',
    projectId: 'bsccs-4a473',
    storageBucket: 'bsccs-4a473.appspot.com',
    androidClientId: '937397677110-pf4o17o6pp25m7ma68dtvcq1gcs8v709.apps.googleusercontent.com',
    iosClientId: '937397677110-l7ri1v7069t5g81ju60jqvccuec0acta.apps.googleusercontent.com',
    iosBundleId: 'com.zee.bsccs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCY1WSWJwqu7OC8IgvEbJbgpIInDLZvHoU',
    appId: '1:937397677110:ios:de0dcd2126d8613588fc97',
    messagingSenderId: '937397677110',
    projectId: 'bsccs-4a473',
    storageBucket: 'bsccs-4a473.appspot.com',
    androidClientId: '937397677110-pf4o17o6pp25m7ma68dtvcq1gcs8v709.apps.googleusercontent.com',
    iosClientId: '937397677110-l7ri1v7069t5g81ju60jqvccuec0acta.apps.googleusercontent.com',
    iosBundleId: 'com.zee.bsccs',
  );
}
