/// Flutter icons BscCsApp
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BscCsApp
///      fonts:
///       - asset: fonts/BscCsApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class BscCsApp {
  BscCsApp._();

  static const _kFontFam = 'BscCsApp';
  static const String? _kFontPkg = null;

  static const IconData questions = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData syllabus = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData books = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData freeCourses = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notes = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData practicals = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
